services:
  mediator-api:
    build: .
    ports:
      - "5024:8080"
    depends_on:
      - sqlserver
    environment:
      - Authorization__ApiKey=9a289c1dbcea472ba913c29fbc9f9391
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Sqlserver0001&
    volumes:
      - sqlserver-data:/var/opt/mssql/data
volumes:
  sqlserver-data: